'use strict';
/**
 * audio/devices — sound card discovery, config CRUD, hardware boost,
 * audio test capture.
 *
 * Routes:
 *   GET /api/audio/devices        — enumerate ALSA capture devices via arecord -l
 *   GET /api/audio/test           — record 5 s + return spectrogram PNG
 *   GET /api/audio/config         — read config/audio_config.json
 *   POST /api/audio/config        — write config; auto-generates ~/.asoundrc
 *                                    when device_id changes (dsnoop multi-app)
 *   GET /api/audio/boost          — read softvol Boost dB (UI gain control)
 *   POST /api/audio/boost         — set Boost dB via amixer + persist via alsactl
 */
const path = require('path');
const fs = require('fs');
const { spawn, exec, execSync } = require('child_process');
const safeConfig = require('../../lib/safe-config');
const { readJsonFile } = require('../../lib/config');
const { AUDIO_CONFIG_PATH, AUDIO_KEYS,
        jsonConfigGet, jsonConfigPost, readBoost } = require('./_helpers');

function handle(req, res, pathname, ctx) {
  const { requireAuth } = ctx;

  // ── Route : GET /api/audio/config ───────────────────────────────────────
  if (req.method === 'GET' && pathname === '/api/audio/config') {
    jsonConfigGet(res, AUDIO_CONFIG_PATH);
    return true;
  }

  // ── Route : POST /api/audio/config ──────────────────────────────────────
  // When device_id changes, auto-generate ~/.asoundrc with a dsnoop slave so
  // multiple processes (recording service + monitor + filter preview) can
  // share the capture device. The actual device_id stored in audio_config
  // becomes "birdash" (the dsnoop alias), and we restart the recording
  // service so it picks up the new device.
  if (req.method === 'POST' && pathname === '/api/audio/config') {
    if (!requireAuth(req, res)) return true;
    const oldDevice = (readJsonFile(AUDIO_CONFIG_PATH) || {}).device_id;
    jsonConfigPost(req, res, AUDIO_CONFIG_PATH, AUDIO_KEYS, async (current, filtered) => {
      if (filtered.device_id && filtered.device_id !== oldDevice) {
        try {
          const devId = filtered.device_id;
          let cardName = '';
          const hwMatch = devId.match(/CARD=(\w+)/);
          if (hwMatch) cardName = hwMatch[1];
          else {
            const arecordOut = execSync('arecord -l 2>/dev/null', { encoding: 'utf8' });
            const cardMatch = arecordOut.match(/card \d+: (\w+) \[/);
            if (cardMatch) cardName = cardMatch[1];
          }
          if (cardName) {
            const channels = current.input_channels || 2;
            const rate = current.capture_sample_rate || 48000;
            const asoundrc = `# Auto-generated by Birdash for ${current.device_name || cardName}\n` +
              `pcm.birdash {\n    type dsnoop\n    ipc_key 2048\n    slave {\n` +
              `        pcm "hw:CARD=${cardName},DEV=0"\n        channels ${channels}\n` +
              `        rate ${rate}\n    }\n}\n`;
            await safeConfig.writeRaw(path.join(process.env.HOME, '.asoundrc'), asoundrc, { label: 'POST /api/audio/config (asoundrc)' });
            await safeConfig.updateConfig(
              AUDIO_CONFIG_PATH,
              (cfg) => { cfg.device_id = 'birdash'; return cfg; },
              null,
              { label: 'POST /api/audio/config (device→birdash)', defaultValue: {} }
            );
            console.log(`[audio] ALSA dsnoop config generated for ${cardName}`);
            try { exec('sudo systemctl restart birdengine-recording'); } catch {}
          }
        } catch (e) {
          console.warn('[audio] ALSA config generation failed:', e.message);
        }
      }
    }, 'POST /api/audio/config');
    return true;
  }

  // ── Route : GET /api/audio/boost ────────────────────────────────────────
  // UI hides the slider when available=false (fresh install, no USB mic, or
  // custom .asoundrc that didn't set up the softvol).
  if (req.method === 'GET' && pathname === '/api/audio/boost') {
    const info = readBoost();
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(info));
    return true;
  }

  // ── Route : POST /api/audio/boost ───────────────────────────────────────
  // Body: { db: number } — applied via amixer, persisted via alsactl store.
  // alsactl needs root, expected via sudoers NOPASSWD. If sudo fails, the
  // value still applies live until reboot.
  if (req.method === 'POST' && pathname === '/api/audio/boost') {
    if (!requireAuth(req, res)) return true;
    let body = '';
    req.on('data', c => body += c);
    req.on('end', () => {
      try {
        const { db } = JSON.parse(body || '{}');
        if (typeof db !== 'number' || !Number.isFinite(db)) {
          throw new Error('db must be a finite number');
        }
        const info = readBoost();
        if (!info.available) throw new Error('Boost control not available');
        const clamped = Math.max(info.min_db, Math.min(info.max_db, db));
        execSync(`amixer -c ${info.card} sset Boost ${clamped.toFixed(2)}dB`, { encoding: 'utf8' });
        try {
          execSync(`sudo -n /usr/sbin/alsactl store ${info.card} 2>/dev/null || /usr/sbin/alsactl store ${info.card} 2>/dev/null || true`);
        } catch {}
        const fresh = readBoost();
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: true, ...fresh }));
      } catch (e) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: e.message }));
      }
    });
    return true;
  }

  // ── Route : GET /api/audio/test ─────────────────────────────────────────
  // Capture 5 s + render a spectrogram PNG (used by Settings → Audio test).
  if (req.method === 'GET' && pathname === '/api/audio/test') {
    (async () => {
      try {
        const config = readJsonFile(AUDIO_CONFIG_PATH) || {};
        const device = config.device_id || 'default';
        const tmpWav = '/tmp/birdash_audio_test.wav';
        const tmpPng = '/tmp/birdash_audio_test.png';
        await new Promise((resolve, reject) => {
          const proc = spawn('arecord', [
            '-D', device, '-f', 'S16_LE', '-r', '48000', '-c', '2',
            '-d', '5', tmpWav
          ]);
          proc.on('close', code => code === 0 ? resolve() : reject(new Error(`arecord exit ${code}`)));
          proc.on('error', reject);
          setTimeout(() => { proc.kill(); reject(new Error('timeout')); }, 10000);
        });
        await new Promise((resolve, reject) => {
          const ff = spawn('ffmpeg', [
            '-y', '-i', tmpWav, '-lavfi', 'showspectrumpic=s=800x400:legend=0:color=intensity',
            '-frames:v', '1', tmpPng
          ]);
          ff.on('close', code => code === 0 ? resolve() : reject(new Error('ffmpeg ' + code)));
          ff.on('error', reject);
        });
        const png = fs.readFileSync(tmpPng);
        try { fs.unlinkSync(tmpWav); fs.unlinkSync(tmpPng); } catch {}
        res.writeHead(200, { 'Content-Type': 'image/png' });
        res.end(png);
      } catch (e) {
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: e.message }));
      }
    })();
    return true;
  }

  // ── Route : GET /api/audio/devices ──────────────────────────────────────
  // Enumerate capture devices via arecord -l, augment each with its
  // hw_params (channels, rates) and a USB-ish tag based on the card name.
  if (req.method === 'GET' && pathname === '/api/audio/devices') {
    (async () => {
      try {
        const { stdout } = await new Promise((resolve) => {
          exec('arecord -l 2>/dev/null', (err, stdout, stderr) => {
            resolve({ stdout: stdout || '', stderr });
          });
        });
        const devices = [];
        const lines = stdout.split('\n');
        for (const line of lines) {
          const m = line.match(/^card (\d+): (\w+) \[(.+?)\], device (\d+): (.+)/);
          if (m) {
            const id = `hw:${m[1]},${m[3 + 1]}`;
            const name = m[3];
            const isUsb = /usb|rode|ai.?micro|scarlett|behringer|zoom|tascam|presonus/i.test(name);
            let channels = 2, rates = [];
            try {
              const { stdout: info } = await new Promise((resolve) => {
                exec(
                  `arecord -D ${id} --dump-hw-params -d 0 2>&1 || true`,
                  { timeout: 3000 },
                  (err, stdout) => resolve({ stdout: stdout || '' })
                );
              });
              const chMatch = info.match(/CHANNELS\s*:.*?(\d+)/s);
              if (chMatch) channels = parseInt(chMatch[1]);
              const rateMatch = info.match(/RATE\s*:\s*(\d+)/);
              if (rateMatch) rates.push(parseInt(rateMatch[1]));
            } catch {}
            const cardName = m[2];
            const dsnoop_id = `dsnoop:CARD=${cardName},DEV=${m[4]}`;
            devices.push({
              id: dsnoop_id,
              hw_id: id,
              name,
              alsa_card: parseInt(m[1]),
              alsa_device: parseInt(m[4]),
              channels,
              sample_rates: rates.length ? rates : [48000],
              usb_audio: isUsb,
            });
          }
        }
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ devices }));
      } catch (e) {
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: e.message }));
      }
    })();
    return true;
  }

  return false;
}

module.exports = { handle };
